{"uuid": "c5242e4e-a742-45a3-a337-a5b5ae2e4b8f", "children": ["de3aa60a-b921-420e-8ef2-838c27e7fe76"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: MSEdge failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from msedge location C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe is no longer running, so MSEdgeDriver is assuming that MSEdge has crashed.)\n\n", "trace": "  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\tests\\conftest.py\", line 16, in setup\n    driver = BrowserInitialization.generateDriver(browser)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\utilities\\BrowserInitialization.py\", line 10, in generateDriver\n    return webdriver.Edge()\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 66, in __init__\n    desired_capabilities=capabilities)\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\programs\\odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1621574307717, "stop": 1621574340126}], "start": 1621574307717, "stop": 1621574340267}